title: "Loretta C. Duckworth Scholars Studio"
description: "Temple University Libraries' hub for digital scholarship, critical making, and immersive technology"
url: "https://templedss.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# Site metadata
temple_logo_url: "https://library.temple.edu/assets/temple-logo-t-box-90cc3fa538df8cb198867442038a1dac87756f1e375393193f775e8760013fdf.svg"
blog_header_image: "https://sites.temple.edu/tudsc/files/2018/10/cover-web-2.jpg"
contact_email: "digitalscholarship@temple.edu"
address: "Charles Library, 1900 N. 13th Street, Philadelphia, PA 19122"
blog_url: "https://sites.temple.edu/tudsc/"
library_url: "https://library.temple.edu/lcdss"
